<?php
/**
 * @file
 * blaa_theme_mobydick.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function blaa_theme_mobydick_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "boxes" && $api == "box") {
    return array("version" => "1");
  }
  list($module, $api) = func_get_args();
  if ($module == "context" && $api == "context") {
    return array("version" => "3");
  }
  list($module, $api) = func_get_args();
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}
